del "EBUCert.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-1-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-2-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-3-16bit-v02.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-4-16bit-v02.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-5-16bit-v02.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-6-5channels-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-6-6channels-WAVEEX-16bit.wav" >> "EBUCert.log" /config:".\r128_map_L_R_C_0_Ls_Rs.ini" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"

"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-7_seq-3342-5-24bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3341-2011-8_seq-3342-6-24bit-v02.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"

"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3342-1-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3342-2-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3342-3-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"
"..\Debug\JOCLoudness.exe" "..\..\..\..\TestFiles\EBU\seq-3342-4-16bit.wav" >> "EBUCert.log" /logsfile:"..\..\..\..\TestFiles\LOGS\JOCLoudness.log"